import { lazy, Suspense, useEffect, useRef, useState } from 'react';
import { flushSync } from 'react-dom';
import { ArrowRight, ArrowUpRight, List, X, MagnifyingGlass, Pause, Play, ArrowClockwise, Cube } from '@phosphor-icons/react';
import { Library, Article } from './Library.jsx';
import { ProductPage, Campaign, OtherActivities, About, Progress, Works, Participation, Text } from './Pages.jsx';
import { Workbench } from './Workbench.jsx';

const StageScene = lazy(() => import('./StageScene.jsx'));
const entries = [
  { id:'show', title:'多人喜剧聊天节目', image:'project-show.png', status:'筹备与招募' },
  { id:'course', title:'AI 与 Codex 课程', image:'project-course.png', status:'线上 199 元 · 深圳线下 399 元' },
  { id:'process', title:'制作记录', image:'project-process.png', status:'作品、过程和方法' },
];
function currentRoute() {
  const q=new URLSearchParams(window.location.search);
  return { page:q.get('project')?'project':q.get('page')||'home', project:q.get('project'), slug:q.get('slug'), category:q.get('category')||'all', query:q.get('q')||'', hash:window.location.hash };
}
function useReducedMotion() {
  const [reduced,setReduced]=useState(()=>window.matchMedia('(prefers-reduced-motion: reduce)').matches);
  useEffect(()=>{const q=window.matchMedia('(prefers-reduced-motion: reduce)');const change=()=>setReduced(q.matches);q.addEventListener('change',change);return()=>q.removeEventListener('change',change)},[]);
  return reduced;
}
function Brand() {return <a className="brand" href="/" aria-label="BB 箱子首页"><img src="/assets/bb-rabbit-mark.png" alt="" width="54" height="54"/><span className="wordmark"><b>BB</b><strong>箱子</strong></span></a>}
function Header({route}) {
  const [open,setOpen]=useState(false);const toggle=useRef(null);
  useEffect(()=>setOpen(false),[route]);
  useEffect(()=>{const escape=e=>{if(e.key==='Escape'&&open){setOpen(false);toggle.current?.focus()}};window.addEventListener('keydown',escape);return()=>window.removeEventListener('keydown',escape)},[open]);
  const links=[['节目','/?project=show',route.project==='show'],['课程与活动','/?project=course',['course','group','activities'].includes(route.project)],['作品','/?page=works',route.page==='works'],['幕后','/?page=library',['library','article'].includes(route.page)],['参与','/?page=join',route.page==='join']];
  return <header className="site-header"><div className="header-inner"><Brand/><div className="header-controls"><a className="search-toggle" href="/?page=search" aria-label="搜索全站公开内容"><MagnifyingGlass size={24}/></a><button ref={toggle} className="menu-button" aria-label={open?'关闭导航':'打开导航'} aria-expanded={open} aria-controls="main-navigation" onClick={()=>setOpen(!open)}>{open?<X size={24}/>:<List size={26}/>}</button></div><nav className={`navigation ${open?'is-open':''}`} id="main-navigation" aria-label="主导航">{links.map(([label,href,active])=><a href={href} key={href} aria-current={active?'page':undefined}>{label}</a>)}<a className="desktop-search" href="/?page=search" aria-label="搜索全站公开内容"><MagnifyingGlass size={24}/></a></nav></div></header>
}
function Hero({reducedMotion}) {
  const [open,setOpen]=useState(false);const [ready,setReady]=useState(false);const [mode,setMode]=useState('all');const [paused,setPaused]=useState(false);const [replay,setReplay]=useState(0);const hero=useRef(null);
  const modes=[['all','主舞台'],['show','聊天桌'],['course','工作台'],['process','制作台']];const selected=entries.find(e=>e.id===mode);
  return <section ref={hero} className={`hero ${open&&ready?'scene-ready':''} ${open?'space-open':''}`} onPointerMove={event=>{if(reducedMotion||event.pointerType==='touch')return;const rect=event.currentTarget.getBoundingClientRect();hero.current.style.setProperty('--look-x',`${((event.clientX-rect.left)/rect.width-.5)*6}px`);hero.current.style.setProperty('--look-y',`${((event.clientY-rect.top)/rect.height-.5)*4}px`)}} aria-labelledby="brand-title">
    <picture className="stage-fallback"><source media="(max-width: 900px)" srcSet="/assets/stage-hero-mobile.png"/><img src="/assets/stage-hero.png" alt="" fetchPriority="high" width="1835" height="857"/></picture>
    {open&&<Suspense fallback={null}><StageScene mode={mode} reducedMotion={reducedMotion} paused={paused} replayKey={replay} onReady={setReady}/></Suspense>}
    <div className="hero-copy"><h1 id="brand-title"><span className="bb-title">BB</span><span>箱子</span></h1><p className="hero-category"><span>聊天节目</span><i>·</i><span>AI 课程</span><i>·</i><span>公开制作</span></p><Text lines={['我们在深圳。','一起做点有意思的事。']} className="hero-description"/><div className="hero-actions"><a className="button primary" href="#projects">探索项目<ArrowRight size={25}/></a><a className="contact-link" href="/#contact">联系 Bono<ArrowRight size={24}/></a></div></div>
    <div className="stage-controls"><button className={`space-toggle ${open?'is-active':''}`} onClick={()=>{setOpen(!open);setReady(false)}} aria-expanded={open}><Cube size={19}/>{open?'回到场景图':'走进三维舞台'}</button>{open&&<><div className="stage-destinations" role="group" aria-label="选择舞台空间">{modes.map(([id,label])=><button key={id} aria-pressed={mode===id} onClick={()=>setMode(id)}>{label}</button>)}</div><div className="motion-controls"><button onClick={()=>setPaused(!paused)} aria-label={paused?'继续舞台动画':'暂停舞台动画'}>{paused?<Play size={16}/>:<Pause size={16}/>}</button><button onClick={()=>{setPaused(false);setReplay(k=>k+1)}} aria-label="重播舞台开场"><ArrowClockwise size={17}/></button></div>{selected&&<a className="space-detail" href={`/?project=${selected.id}`}>{selected.title}<ArrowUpRight size={19}/></a>}</>}<span className="scene-note">{open?'概念空间':'场景示意'}</span></div>
  </section>;
}
function Home({reducedMotion}) {return <><Hero reducedMotion={reducedMotion}/><section className="projects" id="projects" aria-label="从三个项目开始"><div className="project-grid">{entries.map((e,i)=><a className="project-entry" href={`/?project=${e.id}`} key={e.id}><div className="project-label"><span className="project-number">0{i+1}</span><h2>{e.title}</h2><ArrowRight size={27}/></div><div className="project-picture"><img src={`/assets/${e.image}`} alt="项目场景示意" width="1942" height="809" style={{viewTransitionName:`project-${e.id}`}}/></div><p className="entry-status">{e.status}</p></a>)}</div><p className="project-caption">项目场景示意</p></section><section className="visitor-routes" aria-label="按你的兴趣继续"><span>你可以从这里开始</span><a href="/?project=show">想来聊天<ArrowRight size={19}/></a><a href="/?project=course">想学 AI 实操<ArrowRight size={19}/></a><a href="/?page=works">先看做出的东西<ArrowRight size={19}/></a><a href="/?page=join">想一起做事<ArrowRight size={19}/></a></section><Workbench/><Campaign/><OtherActivities/><About brief/><Progress brief/><section className="archive-intro section-pad"><div><h2><span>看完成品，</span><span>再往里走。</span></h2><Text lines={['怎么做的，改过什么。','规则、代码和方法，都可以看。']}/></div><div className="archive-paths"><a href="/?page=library&category=updates"><span>制作与进展</span><ArrowRight size={26}/></a><a href="/?page=library&category=guide"><span>参与与规则</span><ArrowRight size={26}/></a><a href="/?page=library&category=method"><span>AI、开源与方法</span><ArrowRight size={26}/></a><a href="/?page=library"><span>全部公开资料</span><ArrowRight size={26}/></a></div></section></>}
export function App() {
  const [route,setRoute]=useState(currentRoute);const reducedMotion=useReducedMotion();const transition=useRef(null);
  const navigate=(href)=>{const url=new URL(href,window.location.origin);const update=()=>{window.history.pushState({},'',url.pathname+url.search+url.hash);flushSync(()=>setRoute(currentRoute()))};transition.current?.skipTransition();if(url.pathname===window.location.pathname&&url.search===window.location.search){update();return;}if(!reducedMotion&&document.startViewTransition){transition.current=document.startViewTransition(update);transition.current.finished.catch(()=>{})}else update()};
  useEffect(()=>{const pop=()=>setRoute(currentRoute());window.addEventListener('popstate',pop);return()=>window.removeEventListener('popstate',pop)},[]);
  useEffect(()=>{const title=route.page==='home'?'聊天节目、AI 课程与公开制作':route.page==='project'?entries.find(e=>e.id===route.project)?.title||({group:'BB箱子问答群',activities:'内容型活动'})[route.project]||'项目':({library:'公开资料',article:'阅读资料',search:'全站搜索',works:'作品与制作',about:'Bono',join:'参与',updates:'近况'})[route.page]||'BB 箱子';document.title=`${title} · BB 箱子`;if(route.hash){requestAnimationFrame(()=>document.getElementById(decodeURIComponent(route.hash.slice(1)))?.scrollIntoView({behavior:'instant',block:'start'}))}else{window.scrollTo({top:0,behavior:'instant'});document.querySelector('#page-heading,#reading-heading,#main')?.focus({preventScroll:true})}},[route]);
  const delegate=(event)=>{const anchor=event.target.closest('a');if(!anchor||anchor.target==='_blank'||anchor.hasAttribute('download')||event.defaultPrevented||event.metaKey||event.ctrlKey||event.shiftKey||event.altKey||event.button!==0)return;const raw=anchor.getAttribute('href');if(!raw)return;if(raw.startsWith('#')){event.preventDefault();navigate(window.location.pathname+window.location.search+raw);return;}const url=new URL(anchor.href);if(url.origin!==window.location.origin||url.pathname!=='/')return;event.preventDefault();navigate(url.href)};
  let page;switch(route.page){case 'project':page=<ProductPage id={route.project}/>;break;case 'library':page=<Library category={route.category}/>;break;case 'article':page=<Article slug={route.slug}/>;break;case 'search':page=<Library query={route.query} search onSearch={q=>navigate(`/?page=search&q=${encodeURIComponent(q)}`)}/>;break;case 'works':page=<Works/>;break;case 'about':page=<About/>;break;case 'join':page=<Participation/>;break;case 'updates':page=<Progress/>;break;default:page=<Home reducedMotion={reducedMotion}/>}
  return <div onClick={delegate}><a className="skip-link" href="#main">跳到正文</a><Header route={route}/><main id="main" tabIndex={-1}>{page}{route.page!=='join'&&<Participation brief/>}</main><footer><a className="footer-brand" href="/">BB 箱子</a><span>本地全站预览 · 2026.10</span><a href="/?page=article&slug=privacy">隐私与统计说明</a><a href="https://github.com/Bono12138/bb-box-show" target="_blank" rel="noopener noreferrer">公开仓库<ArrowUpRight size={17}/></a></footer></div>;
}
