import { useState } from 'react';
import { ArrowRight, ArrowLeft, ArrowUpRight, DownloadSimple } from '@phosphor-icons/react';
import { products, updates, participation, articleHref } from './data/catalogue.js';
import { Workbench } from './Workbench.jsx';
import { ReadingText } from './Library.jsx';

export function Text({lines,className=''}) {return <p className={className}>{lines.map((line,i)=><span className="semantic-line" key={i}>{line}</span>)}</p>}
const link=slug=>articleHref(slug);
const variants=[
  {id:'A',label:'入门',title:['第一次上手。','做个能打开的项目。'],copy:['先把工具准备好。','练习怎样交代任务、准备资料。','制作之后，检查它交来的结果。']},
  {id:'B',label:'办公',title:['表格、报告、PPT。','让 AI 先出一版。'],copy:['整理资料、表格与报告。','核对数字，再整理成汇报。','把重复步骤留下来，下次继续用。']},
  {id:'C',label:'网页',title:['想做一个网站？','从想法走到发布。'],copy:['先讲清楚它给谁用。','把页面、内容和互动做出来。','检查手机体验，再准备发布。']},
  {id:'D',label:'创作',title:['办活动，做宣传。','把一整套素材做出来。'],copy:['海报、PPT 和介绍页。','安排素材、文案和视觉。','制作与修改，也留下记录。']},
  {id:'E',label:'AI 工作台',title:['留住自己的方法。','做成 AI 工作台。'],copy:['项目资料、Skills 和工具。','让多个 Agent 分工，再检查。','把能复用的流程保存下来。']},
];
const stations=[
  ['第一次上手',['课前准备网络、账号与产品订阅。','ChatGPT 与 Codex 分工。','任务的规划、执行和检查。']],
  ['让结果更像你要的',['准备项目资料。','AGENTS.md 与 DESIGN.md。','准备素材，写清楚要求。','用真实修改检查结果。']],
  ['下次不用从头做',['Skills：留下能重复使用的做法。','MCP：连接外部工具和资料。','浏览器工具与自动化。']],
  ['做出能打开的项目',['文档、表格、PPT 与网页。','Git／GitHub 管理版本。','检查、发布与商业化准备。']],
  ['自己的 AI 工作台',['多 Agent 协作与任务安排。','结果复核、资料整理和版本记录。','逐步建立自己的工作方式。']],
];
export function Campaign({detail=false}) {
  const [chosen,setChosen]=useState('A');const variant=variants.find(v=>v.id===chosen);
  return <section className="campaign-section section-pad" id="course-directions"><div className="campaign-top"><div><h2><span>同一堂课。</span><span>五种打开方式。</span></h2><Text lines={['先选你关心的方向。','课程内容相同。']}/></div><div className="campaign-tabs" role="group" aria-label="课程宣传方向">{variants.map(v=><button key={v.id} onClick={()=>setChosen(v.id)} aria-pressed={chosen===v.id}>{v.label}</button>)}</div></div><div className="campaign-layout"><a className="campaign-poster" key={chosen} href={`/assets/campaign/${chosen}.png`} target="_blank" rel="noopener noreferrer" aria-label={`查看${variant.label}方向课程封面`}><img src={`/assets/campaign/${chosen}.png`} alt={`${variant.label}方向课程宣传海报，点击查看封面原图`} width="1080" height="1440" loading="lazy"/><span>打开原图<ArrowUpRight size={18}/></span></a><div className="campaign-copy"><h3>AI 与 Codex 实操课</h3><p className="course-prices"><span>线上 ¥199</span><span>深圳线下 ¥399</span></p><h4>{variant.title.map(t=><span key={t}>{t}</span>)}</h4><Text lines={variant.copy}/><Text lines={['一节完整实操课。','任务、工具、作品与检查。','把整个过程走一遍。']} className="course-completeness"/><a className="text-link" href={detail?'#syllabus':'/?project=course'}>查看完整课纲<ArrowRight size={22}/></a><p className="small-note"><span className="semantic-line">海报是本地制作的宣传材料。</span><span className="semantic-line">具体场次与权益，以活动说明为准。</span></p></div></div></section>
}
function Syllabus() {return <section className="syllabus section-pad" id="syllabus"><h2><span>任务要做完。</span><span>结果要检查。</span></h2><Text lines={['完整课程范围放在这里。','报名之前，说明课时与练习。','现场安排也一起说明。']}/><ol>{stations.map(([title,lines],i)=><li key={title}><span className="station-number">0{i+1}</span><h3>{title}</h3><Text lines={lines}/></li>)}</ol><div className="support-note"><h3>课前，先把工具准备好。</h3><Text lines={['课前协助准备网络环境。','账号与产品订阅也一起准备。','第三方产品费用另付。','是否购买，由你决定。']}/><Text lines={['可以选择其他 Agent 产品。','功能与练习的适配，另行说明。','回看与更新：见活动说明。','赠群条件：见活动说明。']}/></div></section>}
export function Programme() {return <section className="programme-notes section-pad"><div><h2><span>有意思，</span><span>也聊得进去。</span></h2><Text lines={['每次围绕一个主话题。','先讲各自的经历。','追问下去，也听不同意见。']}/></div><div><p className="format-note">主要中文 · 4–6 人，包含主持人</p><ol className="topic-thread"><li><b>主话题</b><span>先找到值得聊的一件事。</span></li><li><b>个人经历</b><span>具体发生了什么？</span></li><li><b>追问与分歧</b><span>为什么？别人怎么看？</span></li><li><b>继续聊下去</b><span>好笑的细节与更深的问题。</span></li></ol><Text lines={['Bono 初期主持，也参与聊天。','照顾时间和每个人的接话机会。','具体话题还没定。','先从真实想法和试聊里找。']}/><a className="text-link" href={link('first-meeting')}>第一次见面怎么聊<ArrowRight size={22}/></a></div></section>}
export function OtherActivities() {return <section className="other-activities section-pad"><h2><span>来玩一次。</span><span>也可以留下来。</span></h2><div className="activities-layout"><article><div><h3>乱讲 PPT</h3><Text lines={['陌生幻灯片，现场硬讲。','形式已确认，排期待定。']}/><a className="button primary" href="/?project=activities">看看怎么玩<ArrowRight size={22}/></a></div><img src="/assets/project-show.png" alt="多人聊天桌，场景示意" loading="lazy"/></article><article><div><h3 className="activity-group-name">BB箱子问答群</h3><p className="annual-price">¥199 / 年</p><Text lines={['AI、自媒体、商业。','Bono 看见问题就回答。','预售期筹备。']}/><a className="button primary" href="/?project=group">了解详情<ArrowRight size={22}/></a></div><img src="/assets/project-course.png" alt="桌面工作台，场景示意" loading="lazy"/></article></div><p className="small-note right-note">活动与工作台配图为场景示意。</p></section>}
export function About({brief=false}) {const Heading=brief?'h2':'h1';return <section className={`about-section section-pad ${brief?'about-brief':''}`}><div className="about-name"><Heading id={!brief?'page-heading':undefined} tabIndex={!brief?-1:undefined}>Bono</Heading><span>BB 箱子发起人</span></div><div className="about-copy"><h2><span>把经历带到桌上。</span><span>把想法做成东西。</span></h2><dl><div><dt>咨询与金融</dt><dd><Text lines={['前安永（EY）咨询师。','曾服务客户：','中国平安集团、平安银行。','建设银行、招商银行。','腾讯、中信保诚。']}/></dd></div><div><dt>当前工作</dt><dd><Text lines={['企业：跨境 fintech 独角兽。','现职：IFRS9 实施负责人。']}/></dd></div><div><dt>活动与项目</dt><dd><Text lines={['Cursor 活动负责人：深圳站、香港站。','BB 箱子初期主持与课程发起人。']}/></dd></div></dl><p className="small-note"><ReadingText text="履历由 Bono 提供。活动组织身份不代表官方讲师认证或企业背书。"/></p><a className="text-link" href={brief?'/?page=about':link('bono')}>{brief?'认识发起人':'看节目里的主持方式'}<ArrowRight size={22}/></a></div></section>}
export function Progress({brief=false}) {const Heading=brief?'h2':'h1';const items=brief?updates.slice(0,3):updates;return <section className="progress-section section-pad"><div className="section-heading"><Heading id={!brief?'page-heading':undefined} tabIndex={!brief?-1:undefined}>最近在忙什么。</Heading><Text lines={['做过的事，留下日期。','正在做的，也说清楚状态。']}/></div><div className="progress-list">{items.map(item=><a href={item.href||link(item.articleSlug)} key={item.id}><time dateTime={item.date}>{item.date}</time><div><h3><ReadingText text={item.title}/></h3><p><ReadingText text={item.summary}/></p><span>{item.status}</span></div><ArrowRight size={26}/></a>)}</div>{brief&&<a className="text-link" href="/?page=updates">全部近况<ArrowRight size={22}/></a>}</section>}
const pageInfo={show:{title:['凑一桌。','把话聊开。'],image:'project-show.png',summary:['在深圳做一档多人喜剧聊天节目。','有意思，也想聊出深度。']},course:{title:['带个想法。','做成作品。'],image:'project-course.png',summary:['完整 AI 与 Codex 实操课。','从任务一路走到结果。']},process:{title:['看看成品。','也看看过程。'],image:'project-process.png',summary:['制作、修改、检查和复盘。','代码与方法，也留下来。']},group:{title:['问题来了。','可以继续问。'],image:'project-course.png',summary:['BB箱子问答群。','AI、自媒体、商业等问题交流。']},activities:{title:['来玩一次，','现场见。'],image:'project-show.png',summary:['用内容把人聚到一起。','乱讲 PPT 等活动正在筹备。']}};
export function ProductPage({id}) {
  const info=pageInfo[id];const product=products.find(p=>p.id===id);if(!info)return <section className="section-pad"><h1 id="page-heading" tabIndex={-1}>这个项目暂未找到。</h1><a href="/">返回首页</a></section>;
  return <><article className={`product-detail detail-${id}`}><header className="product-intro section-pad"><a className="back-link" href="/#projects"><ArrowLeft size={20}/>返回项目</a><div className="product-meta"><span>{product?.label||product?.title}</span><span>{product?.status}</span></div><h1 id="page-heading" tabIndex={-1}>{info.title.map(line=><span key={line}>{line}</span>)}</h1><Text className="product-lede" lines={info.summary}/><ul className="product-facts">{product?.facts?.map(fact=><li key={fact}>{fact}</li>)}</ul></header><figure className="product-image"><img src={`/assets/${info.image}`} alt="项目场景示意" width="1942" height="809" style={['show','course','process'].includes(id)?{viewTransitionName:`project-${id}`}:{}}/><figcaption>场景示意</figcaption></figure>
    {id==='show'&&<><Programme/><section className="section-pad linked-reading"><h2>先认识，再试聊。</h2><Text lines={['不用提前把每句话写成段子。','愿意讲自己的经历。','也愿意听别人讲。']}/><a className="text-link" href={link('chat-guide')}>聊天成员参与指南<ArrowRight size={22}/></a><a className="text-link" href={link('pilot-procedure')}>试录怎么安排<ArrowRight size={22}/></a><a className="text-link" href={link('rights')}>素材、署名与退出<ArrowRight size={22}/></a></section></>}
    {id==='course'&&<><Campaign detail/><Syllabus/><section className="section-pad course-enrol"><h2>了解清楚，再报名。</h2><Text lines={['线上 199 元。深圳线下 399 元。','场次、时长和地点：见活动页。','公开下单链接仍在核验。']}/><a className="text-link" href={link('course-overview')}>完整课程与服务说明<ArrowRight size={22}/></a><a className="text-link" href="/?page=join">联系与合作入口<ArrowRight size={22}/></a></section></>}
    {id==='group'&&<section className="section-pad linked-reading"><h2>BB箱子问答群</h2><p className="annual-price">199 元 / 年</p><Text lines={['Bono 看见问题就回答。','不设会员总人数上限。','目前处于预售期筹备。','起算、续费与退款：加入前说明。','赠群条件：加入前说明。']}/><a className="text-link" href={link('group-overview')}>群的内容与加入条件<ArrowRight size={22}/></a></section>}
    {id==='activities'&&<section className="section-pad linked-reading"><h2>乱讲 PPT</h2><Text lines={['给你一份陌生的 PPT。','现场接着讲，大家一起听。','活动形式已确认。','玩法、价格和排期：','见后续活动说明。']}/><a className="text-link" href={link('activities-overview')}>活动说明与筹备状态<ArrowRight size={22}/></a></section>}
    {id==='process'&&<><section className="section-pad process-intro"><h2><span>找到感兴趣的。</span><span>接着看下去。</span></h2><div className="process-entry-list">{[['作品',['海报、演示与 PPT 样稿。'],'/?page=works'],['实际进展',['日期、版本、修改和检查。'],'/?page=updates'],['拿走方法',['清单、模板与工作记录。'],'/?page=library&category=method'],['AI 怎样参与',['记录任务与输入。','留下人工修改和错误。'],link('ai-workflow')]].map(([t,s,h],i)=><a href={h} key={t}><b>0{i+1}</b><div><h3>{t}</h3><Text lines={s}/></div><ArrowRight size={25}/></a>)}</div></section><section className="section-pad linked-reading"><h2><span>拿走方法。</span><span>先看一眼许可。</span></h2><Text lines={['自有代码使用 MIT。','方法文档：CC BY-SA 4.0。','品牌与节目影像：单独授权。','第三方素材：按素材条件使用。']}/><a className="text-link" href={link('open-source')}>开源与素材使用说明<ArrowRight size={22}/></a></section></>}
    <section className="section-pad product-more"><a className="text-link" href={link(product?.articleSlug)}>阅读完整说明<ArrowRight size={22}/></a><a className="text-link" href="/?page=library">继续看公开资料<ArrowRight size={22}/></a></section></article>{id==='course'&&<OtherActivities/>}</>;
}
export function Works() {return <><header className="works-intro section-pad"><h1 id="page-heading" tabIndex={-1}>先看做出来的。</h1><Text lines={['可操作的演示、真实海报、PPT 样稿。','作品旁边，保留它现在的状态。']}/><nav className="works-nav"><a href="#workbench">报价交互</a><a href="#course-directions">五套海报</a><a href="#ppt-sample">课程 PPT</a><a href="#work-notes">制作记录</a></nav></header><Workbench standalone/><Campaign/><section className="ppt-showcase section-pad" id="ppt-sample"><div><h2><span>课程 PPT 也是作品。</span></h2><Text lines={['14 页本地样稿。','已经做过导入和逐页检查。','后续课程内容仍在补充。']}/><a className="text-link" href="/downloads/course-sample.pptx" download>下载可编辑 PPT 样稿<DownloadSimple size={22}/></a></div><a href="/assets/ppt-cover.png" target="_blank" rel="noopener noreferrer"><img src="/assets/ppt-cover.png" alt="BB 箱子 Codex 实操课 PPT 样稿封面" loading="lazy"/></a></section><section className="section-pad work-notes" id="work-notes"><h2><span>制作仍在继续。</span><span>每步都留下记录。</span></h2><Text lines={['视频与空间复刻还在修改。','宣传片仍未定稿。','查看记录，知道做到了哪一步。']}/><a className="text-link" href={link('office-film-progress')}>办公宣传片的当前状态<ArrowRight size={22}/></a><a className="text-link" href={link('course-campaign-progress')}>五套海报的制作与检查<ArrowRight size={22}/></a><a className="text-link" href={link('website-prototype-progress')}>官网的制作与检查<ArrowRight size={22}/></a></section></>}
export function Participation({brief=false}) {const Heading=brief?'h2':'h1';return <section className={`contact-section ${brief?'contact-brief':'contact-full'}`} id="contact"><div><Heading id={!brief?'page-heading':undefined} tabIndex={!brief?-1:undefined}>{brief?<span>一起做点东西。</span>:<><span>想来试试？</span><span>看看怎么参与。</span></>}</Heading><Text lines={['先填写意向。','再聊时间和参与方式。','申请不等于成为成员。','录制和公开授权另行确认。']}/><a className="text-link" href={link('new-friend-guide')}>新朋友从这里开始<ArrowRight size={22}/></a>{!brief&&<Text className="small-note" lines={['微信号与二维码尚未接入。','先使用下面的公开表单联系。']}/>}</div><div className="contact-options">{participation.map(item=><div className="contact-role" key={item.id}><a href={item.url||item.href} target="_blank" rel="noopener noreferrer"><span>{item.title}</span><ArrowUpRight size={25}/></a>{!brief&&<p><ReadingText text={item.summary}/></p>}<a className="role-guide" href={link(item.articleSlug)}>先读参与说明<ArrowRight size={17}/></a></div>)}{!brief&&<div className="contact-rules"><h2>开始之前，讲清楚。</h2>{[['费用与贡献讨论稿','revenue'],['署名、素材与退出','rights'],['录制授权确认清单','recording-consent'],['个人资料怎么处理','privacy']].map(([t,s])=><a href={link(s)} key={s}>{t}<ArrowRight size={19}/></a>)}</div>}</div></section>}
